-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.roles
(
    roleid character varying(50) COLLATE pg_catalog."default" NOT NULL,
    rolename character varying(50) COLLATE pg_catalog."default" NOT NULL,
    activestatus boolean NOT NULL,
    CONSTRAINT roles_pkey PRIMARY KEY (roleid)
);

CREATE TABLE IF NOT EXISTS public.users
(
    id character varying(50) COLLATE pg_catalog."default" NOT NULL,
    email character varying(50) COLLATE pg_catalog."default" NOT NULL,
    password character varying(200) COLLATE pg_catalog."default" NOT NULL,
    roleid character varying(50) COLLATE pg_catalog."default" NOT NULL,
    accesstoken character varying(350) COLLATE pg_catalog."default",
    refreshtoken character varying(350) COLLATE pg_catalog."default",
    activestatus boolean NOT NULL,
    failaccess integer,
    lastfail timestamp without time zone,
    actiontoken character varying(200) COLLATE pg_catalog."default",
    actionperiod time without time zone,
    isHaveToResetPw boolean,
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT users_uemail UNIQUE (email)
);

ALTER TABLE IF EXISTS public.users
    ADD CONSTRAINT fk_roles FOREIGN KEY (roleid)
    REFERENCES public.roles (roleid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;
CREATE INDEX IF NOT EXISTS fki_fk_roles
    ON public.users(roleid);

END;